"""
DataLoaders for different environment datasets.

Three loader classes, one per data format:
- DoubleIntegratorLQRData: p2p_cost, p2p_cost_small (task = goal state)
- VaryingDynamicsData: p2p_dynamics, quadrotor (task = dynamics config)
- ObstacleAvoidanceImitation: obstacle (task = obstacle configuration)
"""

import jax
import jax.numpy as jnp
import numpy as np
import random

from abc import ABC, abstractmethod
from typing import List, Tuple, Optional, Dict
from src.envs.dynamics_models import LinearModelParams


class TaskDataSet(ABC):
    @abstractmethod
    def get_task(self):
        raise NotImplementedError()

    @abstractmethod
    def get_train_test_split(self):
        raise NotImplementedError()

    @abstractmethod
    def sample(self):
        raise NotImplementedError()


class ObstacleAvoidanceImitation(TaskDataSet):
    """
    Data loader for obstacle avoidance trajectories generated by CasADi optimization.

    Expects dataset format from create_obstacle.py:
        dataset = {
            "task_1": {"obstacles": (num_obs, 3), "states": (num_traj, 4, N+1), "actions": (num_traj, 2, N)},
            "task_2": ...
        }

    Each task represents a different obstacle configuration. The class splits tasks into
    train/test sets and can sample K trajectories along with their obstacle contexts.
    """

    def __init__(self, dataset: dict, train_perc: float, normalize: bool = False, seed: int = 42):
        super().__init__()

        self.task_keys = [key for key in dataset.keys() if key.startswith("task_")]
        assert len(self.task_keys) > 0, "No tasks found in dataset (expected keys like 'task_1', 'task_2', ...)"

        for task_key in self.task_keys:
            task_data = dataset[task_key]
            assert "obstacles" in task_data, f"{task_key} missing 'obstacles' key"
            assert "states" in task_data, f"{task_key} missing 'states' key"
            assert "actions" in task_data, f"{task_key} missing 'actions' key"
            assert task_data["states"].ndim == 3, f"{task_key} states should be 3D (num_traj, state_dim, timesteps)"
            assert task_data["actions"].ndim == 3, f"{task_key} actions should be 3D (num_traj, action_dim, timesteps)"
            assert task_data["obstacles"].ndim == 2, f"{task_key} obstacles should be 2D (num_obs, 3)"

        self.dataset = dataset
        self.train_perc = train_perc
        self.seed = seed
        self.train_data, self.test_data = self.get_train_test_split(train_perc)

        self.normalize = normalize
        if normalize:
            self.max_vel = jnp.abs(self.dataset[self.task_keys[0]]["states"][:, 2:, :]).max()
            self.max_pos = jnp.abs(self.dataset[self.task_keys[0]]["states"][:, :2, :]).max()
            all_max_actions = [jnp.abs(self.dataset[k]["actions"]).max() for k in self.task_keys]
            self.max_action = jnp.max(jnp.array(all_max_actions))
        else:
            self.max_vel = 1.0
            self.max_pos = 1.0
            self.max_action = 1.0

        # Pre-group tasks by obstacle count for efficient fixed-shape batching
        self._train_by_count = self._group_by_obs_count(self.train_data)
        self._test_by_count = self._group_by_obs_count(self.test_data)

    def _group_by_obs_count(self, split_data: list) -> dict:
        """Group tasks by their obstacle count."""
        groups = {}
        for task in split_data:
            n = task["obstacles"].shape[0]
            groups.setdefault(n, []).append(task)
        return groups

    def get_train_test_split(self, train_perc: float) -> Tuple[list, list]:
        """Randomly split tasks into train/test sets based on train_perc."""
        num_tasks = len(self.task_keys)
        num_train = int(num_tasks * train_perc)

        task_indices = list(range(num_tasks))
        random.seed(self.seed)
        random.shuffle(task_indices)
        train_task_indices = task_indices[:num_train]
        test_task_indices = task_indices[num_train:]

        train_data = [self.dataset[self.task_keys[idx]] for idx in train_task_indices]
        test_data = [self.dataset[self.task_keys[idx]] for idx in test_task_indices]

        return train_data, test_data

    def get_task(self, type_: str = "train", H: int = -1, K: int = 1):
        """Sample K trajectories from one random task."""
        data = self.train_data if type_ == "train" else self.test_data
        if len(data) == 0:
            raise Exception(f"No {type_} tasks available")
        task_data = data[np.random.choice(len(data))]
        return self._get_task_data(task_data, K)

    def sample(self, type_: str = "train", H: int = -1, M: int = 1, K: int = 1, key=None):
        """
        Sample M tasks, all with the same obstacle count, stacked for vmap.

        Picks one obstacle count per batch so all M tasks have identical shapes.

        Returns stacked arrays:
            states:    (M, K, timesteps, state_dim)  - normalized
            time:      (M, K, timesteps)              - normalized [0, 1]
            actions:   (M, K, timesteps, action_dim)
            obstacles: (M, num_obs, 3)               - normalized, no padding
        """
        groups = self._train_by_count if type_ == "train" else self._test_by_count
        if not groups:
            raise Exception(f"No {type_} tasks available")

        count = int(np.random.choice(list(groups.keys())))
        task_pool = groups[count]

        all_states, all_time, all_actions, all_obstacles = [], [], [], []
        for _ in range(M):
            task_data = task_pool[np.random.choice(len(task_pool))]
            s, t, a, o = self._get_task_data(task_data, K)
            all_states.append(s)
            all_time.append(t)
            all_actions.append(a)
            all_obstacles.append(o)

        return (
            jnp.stack(all_states),
            jnp.stack(all_time),
            jnp.stack(all_actions),
            jnp.stack(all_obstacles),
        )

    def _get_task_data(self, task_data: dict, K: int):
        """Extract and normalize K trajectories from a single task dict."""
        num_traj = task_data["states"].shape[0]
        replace = K > num_traj
        indices = np.random.choice(num_traj, size=K, replace=replace)

        states = jnp.array(task_data["states"][indices])
        states = jnp.transpose(states, (0, 2, 1))
        states = states.at[:, :, :2].set(states[:, :, :2] / self.max_pos)
        states = states.at[:, :, 2:].set(states[:, :, 2:] / self.max_vel)

        timesteps = states.shape[1]
        time = jnp.arange(timesteps, dtype=jnp.float32) / (timesteps - 1)
        time_broadcast = jnp.broadcast_to(time[None, :], (K, timesteps))

        actions = jnp.array(task_data["actions"][indices])
        actions = jnp.transpose(actions, (0, 2, 1))
        actions = actions / self.max_action

        obstacles = jnp.array(task_data["obstacles"]) / self.max_pos

        return states, time_broadcast, actions, obstacles


class VaryingDynamicsData(TaskDataSet):
    """
    Data loader for trajectories with varying dynamics (p2p_dynamics, quadrotor).

    Tasks are defined by dynamics configurations. Each task has trajectories for
    one or more goal states with different start positions.
    """
    keys: List[str] = ["states", "actions", "costs", "dynamics_params", "dynamics_indices", "goal_states"]

    @classmethod
    def load_for_goal(cls, goal_idx: int, dataset: dict, train_perc: float, normalize: bool = False):
        """Load dataset filtered for a fixed goal state."""
        goal_mask = (dataset["goal_indices"] == goal_idx)
        filtered_dataset = {key: value for key, value in dataset.items()}
        for key, value in dataset.items():
            if type(value) is np.ndarray:
                if len(value.shape) > 0:
                    if value.shape[0] == len(goal_mask):
                        filtered_dataset[key] = value[goal_mask]

        return cls(filtered_dataset, train_perc, normalize=normalize)

    def __init__(self, dataset: dict, train_perc: float, normalize: bool = False):
        super().__init__()

        for key in self.keys:
            assert key in dataset.keys(), f"{key} expected in dataset"

        self.dataset = dataset
        self.num_tasks = len(dataset["dynamics_params"])
        self.train_perc = train_perc
        self.normalize = normalize
        self.train_data, self.test_data, self.train_indices, self.test_indices = \
            self.get_train_test_split(dataset, train_perc)

        self.max_action = float(np.abs(dataset["actions"]).max())

    def get_train_test_split(self, data_set: dict, train_perc: float) -> Tuple:
        """Randomly split by dynamics configuration into train/test sets."""
        num_tasks = self.num_tasks
        num_train = int(num_tasks * train_perc)
        idxs_ = list(range(num_tasks))
        train_tasks = random.sample(idxs_, num_train)
        test_tasks = [idx for idx in idxs_ if idx not in train_tasks]

        dynamics_params = [LinearModelParams(*d) for d in data_set["dynamics_params"]]

        def dyn_params_to_array(dyn_params):
            return np.array([list(d) for d in dyn_params])

        params_array = dyn_params_to_array(dynamics_params)

        train_indices = np.isin(data_set["dynamics_indices"], train_tasks)
        test_indices = np.isin(data_set["dynamics_indices"], test_tasks)

        train_params_array = params_array[data_set["dynamics_indices"][train_indices]]
        test_params_array = params_array[data_set["dynamics_indices"][test_indices]]

        train_data = {
            "states": self.dataset["states"][train_indices],
            "actions": self.dataset["actions"][train_indices],
            "costs": self.dataset["costs"][train_indices],
            "dynamics": train_params_array,
            "goal_states": self.dataset["goal_states"][data_set["goal_indices"][train_indices]],
        }

        test_data = {
            "states": self.dataset["states"][test_indices],
            "actions": self.dataset["actions"][test_indices],
            "costs": self.dataset["costs"][test_indices],
            "dynamics": test_params_array,
            "goal_states": self.dataset["goal_states"][data_set["goal_indices"][test_indices]],
        }

        return train_data, test_data, train_indices, test_indices

    def get_task(self, type_: str, K: int, N: int):
        """
        Get task data for a specific dynamics configuration.

        Args:
            type_: "train" or "test"
            K: Number of random (state, action, next_state, cost) tuples
            N: Number of expert trajectories

        Returns:
            Tuple of (random_states, random_actions, random_next_states, random_costs,
                      expert_trajectories, expert_actions, expert_goal_states, dynamics_params)
        """
        if type_ == "train":
            task_indices = self.train_indices
        elif type_ == "test":
            task_indices = self.test_indices
        else:
            raise Exception("Invalid task type should be train or test")

        available_tasks = np.unique(self.dataset["dynamics_indices"][task_indices])
        task_idx = np.random.choice(available_tasks)

        task_mask = (self.dataset["dynamics_indices"] == task_idx) & task_indices
        task_trajectory_indices = np.where(task_mask)[0]

        if len(task_trajectory_indices) == 0:
            raise ValueError(f"No trajectories found for task {task_idx} in {type_} set")

        # Part 1: Random (state, action, next_state, cost) tuples
        all_transitions = []
        for traj_idx in task_trajectory_indices:
            states_traj = self.dataset["states"][traj_idx]
            actions_traj = self.dataset["actions"][traj_idx]
            costs_traj = self.dataset["costs"][traj_idx]

            if len(costs_traj.shape) > 1:
                costs_traj = costs_traj.squeeze()

            for t in range(len(actions_traj)):
                all_transitions.append({
                    'state': states_traj[t],
                    'action': actions_traj[t],
                    'next_state': states_traj[t + 1],
                    'cost': costs_traj[t]
                })

        if K > len(all_transitions):
            sampled_indices = np.random.choice(len(all_transitions), size=K, replace=True)
        else:
            sampled_indices = np.random.choice(len(all_transitions), size=K, replace=False)

        random_states = np.array([all_transitions[i]['state'] for i in sampled_indices])
        random_actions = np.array([all_transitions[i]['action'] for i in sampled_indices])
        random_next_states = np.array([all_transitions[i]['next_state'] for i in sampled_indices])
        random_costs = np.array([all_transitions[i]['cost'] for i in sampled_indices])

        # Part 2: Expert trajectories with goal states
        if N > len(task_trajectory_indices):
            sampled_traj_indices = np.random.choice(task_trajectory_indices, size=N, replace=True)
        else:
            sampled_traj_indices = np.random.choice(task_trajectory_indices, size=N, replace=False)

        expert_trajectories = self.dataset["states"][sampled_traj_indices]
        time = np.arange(expert_trajectories.shape[1])[:, None]
        time_broadcast = np.repeat(time[None, :, :], expert_trajectories.shape[0], axis=0)
        expert_trajectories = np.concatenate([expert_trajectories, time_broadcast], axis=-1)
        expert_actions = self.dataset["actions"][sampled_traj_indices]

        if self.normalize:
            random_actions = random_actions / self.max_action
            expert_actions = expert_actions / self.max_action

        goal_indices_for_trajs = self.dataset["goal_indices"][sampled_traj_indices]
        expert_goal_states = self.dataset["goal_states"][goal_indices_for_trajs][:, None, :]
        expert_goal_states = np.repeat(expert_goal_states, expert_actions.shape[1], axis=1)

        dynamics_params = self.dataset["dynamics_params"][task_idx]

        return (random_states, random_actions, random_next_states, random_costs,
                expert_trajectories, expert_actions, expert_goal_states, dynamics_params)

    def get_meta_task_dynamics(self, type_: str, K_train: int, N_train: int, K_test: int, N_test: int):
        """
        Get meta-learning task data for dynamics-based training.

        Samples two sets of data from the same dynamics configuration:
        - Meta-train: Used for adaptation/inner loop
        - Meta-test: Used for evaluation/outer loop
        """
        if type_ == "train":
            task_indices = self.train_indices
        elif type_ == "test":
            task_indices = self.test_indices
        else:
            raise Exception("Invalid task type should be train or test")

        available_tasks = np.unique(self.dataset["dynamics_indices"][task_indices])
        task_idx = np.random.choice(available_tasks)

        task_mask = (self.dataset["dynamics_indices"] == task_idx) & task_indices
        task_trajectory_indices = np.where(task_mask)[0]

        if len(task_trajectory_indices) == 0:
            raise ValueError(f"No trajectories found for task {task_idx} in {type_} set")

        def sample_data(K, N, traj_indices):
            all_transitions = []
            for traj_idx in traj_indices:
                states_traj = self.dataset["states"][traj_idx]
                actions_traj = self.dataset["actions"][traj_idx]
                costs_traj = self.dataset["costs"][traj_idx]

                if len(costs_traj.shape) > 1:
                    costs_traj = costs_traj.squeeze()

                for t in range(len(actions_traj)):
                    all_transitions.append({
                        'state': states_traj[t],
                        'action': actions_traj[t],
                        'next_state': states_traj[t + 1],
                        'cost': costs_traj[t]
                    })

            if K > len(all_transitions):
                sampled_indices = np.random.choice(len(all_transitions), size=K, replace=True)
            else:
                sampled_indices = np.random.choice(len(all_transitions), size=K, replace=False)

            random_states = np.array([all_transitions[i]['state'] for i in sampled_indices])
            random_actions = np.array([all_transitions[i]['action'] for i in sampled_indices])
            random_next_states = np.array([all_transitions[i]['next_state'] for i in sampled_indices])
            random_costs = np.array([all_transitions[i]['cost'] for i in sampled_indices])

            if N > len(traj_indices):
                sampled_traj_indices = np.random.choice(traj_indices, size=N, replace=True)
            else:
                sampled_traj_indices = np.random.choice(traj_indices, size=N, replace=False)

            expert_trajectories = self.dataset["states"][sampled_traj_indices]
            time = np.arange(expert_trajectories.shape[1])[:, None]
            time_broadcast = np.repeat(time[None, :, :], expert_trajectories.shape[0], axis=0)
            expert_trajectories = np.concatenate([expert_trajectories, time_broadcast], axis=-1)
            expert_actions = self.dataset["actions"][sampled_traj_indices]

            if self.normalize:
                random_actions = random_actions / self.max_action
                expert_actions = expert_actions / self.max_action

            goal_indices_for_trajs = self.dataset["goal_indices"][sampled_traj_indices]
            expert_goal_states = self.dataset["goal_states"][goal_indices_for_trajs][:, None, :]
            expert_goal_states = np.repeat(expert_goal_states, expert_actions.shape[1], axis=1)

            return (random_states, random_actions, random_next_states, random_costs,
                    expert_trajectories, expert_actions, expert_goal_states)

        meta_train_data = sample_data(K_train, N_train, task_trajectory_indices)
        meta_test_data = sample_data(K_test, N_test, task_trajectory_indices)

        dynamics_params = self.dataset["dynamics_params"][task_idx]

        meta_train_data = meta_train_data + (dynamics_params,)
        meta_test_data = meta_test_data + (dynamics_params,)

        return meta_train_data, meta_test_data

    def get_meta_task_cost(self, type_: str, K_train: int, N_train: int, K_test: int, N_test: int):
        """
        Get meta-learning task data for cost-based training.

        Returns (state, action, cost) for branch input instead of (state, action, next_state).
        Task = dynamics config + goal state.
        """
        if type_ == "train":
            task_indices = self.train_indices
        elif type_ == "test":
            task_indices = self.test_indices
        else:
            raise Exception("Invalid task type should be train or test")

        available_tasks = np.unique(self.dataset["dynamics_indices"][task_indices])
        task_idx = np.random.choice(available_tasks)

        dynamics_mask = (self.dataset["dynamics_indices"] == task_idx) & task_indices
        dynamics_trajectory_indices = np.where(dynamics_mask)[0]

        if len(dynamics_trajectory_indices) == 0:
            raise ValueError(f"No trajectories found for task {task_idx} in {type_} set")

        available_goals = np.unique(self.dataset["goal_indices"][dynamics_trajectory_indices])
        goal_idx = np.random.choice(available_goals)

        task_mask = (self.dataset["dynamics_indices"] == task_idx) & \
                    (self.dataset["goal_indices"] == goal_idx) & \
                    task_indices
        task_trajectory_indices = np.where(task_mask)[0]

        if len(task_trajectory_indices) == 0:
            raise ValueError(f"No trajectories found for dynamics {task_idx} and goal {goal_idx} in {type_} set")

        def sample_data(K, N, traj_indices):
            all_transitions = []
            for traj_idx in traj_indices:
                states_traj = self.dataset["states"][traj_idx]
                actions_traj = self.dataset["actions"][traj_idx]
                costs_traj = self.dataset["costs"][traj_idx]

                if len(costs_traj.shape) > 1:
                    costs_traj = costs_traj.squeeze()

                for t in range(len(actions_traj)):
                    all_transitions.append({
                        'state': states_traj[t],
                        'action': actions_traj[t],
                        'cost': costs_traj[t]
                    })

            if K > len(all_transitions):
                sampled_indices = np.random.choice(len(all_transitions), size=K, replace=True)
            else:
                sampled_indices = np.random.choice(len(all_transitions), size=K, replace=False)

            random_states = np.array([all_transitions[i]['state'] for i in sampled_indices])
            random_actions = np.array([all_transitions[i]['action'] for i in sampled_indices])
            random_costs = np.array([all_transitions[i]['cost'] for i in sampled_indices])

            sampled_traj_indices = np.random.choice(traj_indices, size=N, replace=False)
            remaining_indices = [idx for idx in traj_indices if idx not in sampled_traj_indices]

            expert_trajectories = self.dataset["states"][sampled_traj_indices]
            time = np.arange(expert_trajectories.shape[1])[:, None]
            time_broadcast = np.repeat(time[None, :, :], expert_trajectories.shape[0], axis=0)
            expert_trajectories = np.concatenate([expert_trajectories, time_broadcast], axis=-1)
            expert_actions = self.dataset["actions"][sampled_traj_indices]

            if self.normalize:
                random_actions = random_actions / self.max_action
                expert_actions = expert_actions / self.max_action

            return (random_states, random_actions, random_costs,
                    expert_trajectories, expert_actions), remaining_indices

        meta_train_data, remaining = sample_data(K_train, N_train, task_trajectory_indices)
        meta_test_data, _ = sample_data(K_test, N_test, remaining)

        dynamics_params = self.dataset["dynamics_params"][task_idx]

        meta_train_data = meta_train_data + (dynamics_params,)
        meta_test_data = meta_test_data + (dynamics_params,)

        return meta_train_data, meta_test_data

    def sample(self, type_: str = "train", H: int = -1, M: int = 1, K: int = 1, N: int = 1):
        """Sample a batch of M tasks."""
        get_task = lambda i: self.get_task(type_, K, N)
        dummy = jax.numpy.array([0] * M)
        return jax.vmap(get_task)(dummy)

    def meta_sample(self, type_: str = "train", H: int = -1, M: int = 1,
                    K_train: int = 1, K_test: int = 1, N: int = 1):
        """Sample a batch of M meta-learning tasks (dynamics-based)."""
        get_task = lambda i: self.get_meta_task_dynamics(type_, K_train, N, K_test, N)
        dummy = jax.numpy.array([0] * M)
        return jax.vmap(get_task)(dummy)

    def meta_sample_cost(self, type_: str = "train", H: int = -1, M: int = 1,
                         K_train: int = 1, K_test: int = 1, N: int = 1):
        """Sample a batch of M meta-learning tasks (cost-based)."""
        get_task = lambda i: self.get_meta_task_cost(type_, K_train, N, K_test, N)
        dummy = jax.numpy.array([0] * M)
        return jax.vmap(get_task)(dummy)


class DoubleIntegratorLQRData(TaskDataSet):
    """
    Data loader for double integrator LQR trajectories (p2p_cost, p2p_cost_small).

    Each task is defined by a different goal state, which determines a different
    immediate cost landscape. Source samples are (state, control, cost) transitions;
    target samples are full trajectories.
    """
    keys: List[str] = ["states", "actions", "costs", "goal_states", "goal_indices"]

    def __init__(self, dataset: dict, train_perc: float, normalize: bool = True):
        super().__init__()

        for key in self.keys:
            assert key in dataset.keys(), f"{key} expected in dataset"

        self.dataset = dataset
        self.num_goals = len(dataset["goal_states"])
        self.train_perc = train_perc
        self.normalize = normalize

        self.Q_weight = dataset.get("Q_weight", 1.0)
        self.R_weight = dataset.get("R_weight", 0.1)
        self.lqr_gains = dataset.get("lqr_gains", None)
        self.lqr_offsets = dataset.get("lqr_offsets", None)

        if normalize and "norm_stats" in dataset:
            self.norm_stats = dataset["norm_stats"]
        elif normalize:
            self.norm_stats = self._compute_norm_stats()
        else:
            self.norm_stats = None

        self.max_action = float(np.abs(dataset["actions"]).max())

        self.train_data, self.test_data, self.train_goal_indices, self.test_goal_indices = \
            self.get_train_test_split(train_perc)

    def _compute_norm_stats(self) -> Dict:
        """Compute normalization statistics from the dataset."""
        states = self.dataset["states"]
        costs = self.dataset["costs"]

        states_flat = states.reshape(-1, states.shape[-1])
        costs_flat = costs.flatten()

        return {
            'state_mean': np.mean(states_flat, axis=0),
            'state_std': np.std(states_flat, axis=0) + 1e-8,
            'cost_mean': np.mean(costs_flat),
            'cost_std': np.std(costs_flat) + 1e-8,
        }

    def get_train_test_split(self, train_perc: float) -> Tuple[dict, dict, np.ndarray, np.ndarray]:
        """Split tasks (goal states) into train/test sets."""
        num_train = int(self.num_goals * train_perc)
        goal_idxs = list(range(self.num_goals))
        random.shuffle(goal_idxs)

        train_goal_indices = np.array(goal_idxs[:num_train])
        test_goal_indices = np.array(goal_idxs[num_train:])

        train_traj_mask = np.isin(self.dataset["goal_indices"], train_goal_indices)
        test_traj_mask = np.isin(self.dataset["goal_indices"], test_goal_indices)

        train_data = {
            "states": self.dataset["states"][train_traj_mask],
            "actions": self.dataset["actions"][train_traj_mask],
            "costs": self.dataset["costs"][train_traj_mask],
            "goal_indices": self.dataset["goal_indices"][train_traj_mask],
        }

        test_data = {
            "states": self.dataset["states"][test_traj_mask],
            "actions": self.dataset["actions"][test_traj_mask],
            "costs": self.dataset["costs"][test_traj_mask],
            "goal_indices": self.dataset["goal_indices"][test_traj_mask],
        }

        return train_data, test_data, train_traj_mask, test_traj_mask

    def _normalize_state(self, state: np.ndarray) -> np.ndarray:
        if self.norm_stats is None:
            return state
        return (state - self.norm_stats['state_mean']) / self.norm_stats['state_std']

    def _normalize_cost(self, cost: np.ndarray) -> np.ndarray:
        if self.norm_stats is None:
            return cost
        return (cost - self.norm_stats['cost_mean']) / self.norm_stats['cost_std']

    def _normalize_action(self, action: np.ndarray) -> np.ndarray:
        return action / self.max_action

    def get_task(self, type_: str, K: int, N: int):
        """
        Get task data for a specific goal state.

        Args:
            type_: "train" or "test"
            K: Number of source (state, control, cost) samples
            N: Number of target trajectories

        Returns:
            Tuple of (src_states, src_controls, src_costs, src_times,
                      tgt_states, tgt_controls, goal_state)
        """
        data = self.train_data if type_ == "train" else self.test_data

        if len(data["states"]) == 0:
            raise ValueError(f"No {type_} data available")

        available_goals = np.unique(data["goal_indices"])
        goal_idx = np.random.choice(available_goals)
        goal_state = self.dataset["goal_states"][goal_idx]

        goal_mask = data["goal_indices"] == goal_idx
        goal_traj_indices = np.where(goal_mask)[0]

        if len(goal_traj_indices) == 0:
            raise ValueError(f"No trajectories found for goal {goal_idx}")

        # Collect all transitions from trajectories of this goal
        all_transitions = []
        for traj_idx in goal_traj_indices:
            states_traj = data["states"][traj_idx]
            actions_traj = data["actions"][traj_idx]
            costs_traj = data["costs"][traj_idx]
            horizon = len(actions_traj)

            if len(costs_traj.shape) > 1:
                costs_traj = costs_traj.squeeze()

            for t in range(horizon):
                all_transitions.append({
                    'state': states_traj[t],
                    'action': actions_traj[t],
                    'cost': costs_traj[t],
                    'time': t / horizon,
                })

        # Sample K source transitions
        if K > len(all_transitions):
            src_indices = np.random.choice(len(all_transitions), size=K, replace=True)
        else:
            src_indices = np.random.choice(len(all_transitions), size=K, replace=False)

        src_states = np.array([all_transitions[i]['state'] for i in src_indices])
        src_controls = np.array([all_transitions[i]['action'] for i in src_indices])
        src_costs = np.array([all_transitions[i]['cost'] for i in src_indices]).reshape(-1, 1)
        src_times = np.array([all_transitions[i]['time'] for i in src_indices]).reshape(-1, 1)

        # Sample N target trajectories
        if N > len(goal_traj_indices):
            tgt_traj_indices = np.random.choice(goal_traj_indices, size=N, replace=True)
        else:
            tgt_traj_indices = np.random.choice(goal_traj_indices, size=N, replace=False)

        tgt_states = data["states"][tgt_traj_indices, :-1, :]
        tgt_controls = data["actions"][tgt_traj_indices]

        if self.normalize:
            src_states = self._normalize_state(src_states)
            tgt_states = self._normalize_state(tgt_states)
            src_costs = self._normalize_cost(src_costs)
            src_controls = self._normalize_action(src_controls)
            tgt_controls = self._normalize_action(tgt_controls)

        # Append normalized time to target states
        horizon = tgt_states.shape[1]
        time_normalized = np.linspace(0.0, 1.0, horizon, endpoint=False)[:, None]
        time_broadcast = np.repeat(time_normalized[None, :, :], tgt_states.shape[0], axis=0)
        tgt_states = np.concatenate([tgt_states, time_broadcast], axis=-1)

        return (src_states, src_controls, src_costs, src_times, tgt_states, tgt_controls, goal_state)

    def get_meta_task(self, type_: str, K_train: int, N_train: int, K_test: int, N_test: int):
        """
        Get meta-learning task data.

        Samples two sets from the same goal state for inner/outer loop.

        Returns:
            Tuple of (meta_train_data, meta_test_data), each containing:
            (src_states, src_controls, src_costs, src_times, tgt_states, tgt_controls, goal_state)
        """
        data = self.train_data if type_ == "train" else self.test_data

        if len(data["states"]) == 0:
            raise ValueError(f"No {type_} data available")

        available_goals = np.unique(data["goal_indices"])
        goal_idx = np.random.choice(available_goals)
        goal_state = self.dataset["goal_states"][goal_idx]

        goal_mask = data["goal_indices"] == goal_idx
        goal_traj_indices = np.where(goal_mask)[0]

        if len(goal_traj_indices) == 0:
            raise ValueError(f"No trajectories found for goal {goal_idx}")

        all_transitions = []
        for traj_idx in goal_traj_indices:
            states_traj = data["states"][traj_idx]
            actions_traj = data["actions"][traj_idx]
            costs_traj = data["costs"][traj_idx]
            horizon = len(actions_traj)

            if len(costs_traj.shape) > 1:
                costs_traj = costs_traj.squeeze()

            for t in range(horizon):
                all_transitions.append({
                    'state': states_traj[t],
                    'action': actions_traj[t],
                    'cost': costs_traj[t],
                    'time': t / horizon,
                })

        def sample_data(K, N, transitions, traj_indices):
            if K > len(transitions):
                src_indices = np.random.choice(len(transitions), size=K, replace=True)
            else:
                src_indices = np.random.choice(len(transitions), size=K, replace=False)

            src_states = np.array([transitions[i]['state'] for i in src_indices])
            src_controls = np.array([transitions[i]['action'] for i in src_indices])
            src_costs = np.array([transitions[i]['cost'] for i in src_indices]).reshape(-1, 1)
            src_times = np.array([transitions[i]['time'] for i in src_indices]).reshape(-1, 1)

            if N > len(traj_indices):
                sampled_traj_indices = np.random.choice(traj_indices, size=N, replace=True)
            else:
                sampled_traj_indices = np.random.choice(traj_indices, size=N, replace=False)

            tgt_states = data["states"][sampled_traj_indices, :-1, :]
            tgt_controls = data["actions"][sampled_traj_indices]

            if self.normalize:
                src_states = self._normalize_state(src_states)
                tgt_states = self._normalize_state(tgt_states)
                src_costs = self._normalize_cost(src_costs)
                src_controls = self._normalize_action(src_controls)
                tgt_controls = self._normalize_action(tgt_controls)

            horizon = tgt_states.shape[1]
            time_normalized = np.linspace(0.0, 1.0, horizon, endpoint=False)[:, None]
            time_broadcast = np.repeat(time_normalized[None, :, :], tgt_states.shape[0], axis=0)
            tgt_states = np.concatenate([tgt_states, time_broadcast], axis=-1)

            return (src_states, src_controls, src_costs, src_times, tgt_states, tgt_controls)

        meta_train_data = sample_data(K_train, N_train, all_transitions, goal_traj_indices) + (goal_state,)
        meta_test_data = sample_data(K_test, N_test, all_transitions, goal_traj_indices) + (goal_state,)

        return meta_train_data, meta_test_data

    def sample(self, type_: str = "train", H: int = -1, M: int = 1, K: int = 1, N: int = 1):
        """Sample a batch of M tasks."""
        get_task = lambda i: self.get_task(type_, K, N)
        dummy = jax.numpy.array([0] * M)
        return jax.vmap(get_task)(dummy)

    def meta_sample(self, type_: str = "train", H: int = -1, M: int = 1,
                    K_train: int = 1, K_test: int = 1, N: int = 1):
        """Sample a batch of M meta-learning tasks."""
        get_task = lambda i: self.get_meta_task(type_, K_train, N, K_test, N)
        dummy = jax.numpy.array([0] * M)
        return jax.vmap(get_task)(dummy)
